stages:
  - build
  - dev
  - prod

variables:
  APP_NAME: "superadmin-front"
  APP_ID: "d35ib0wh4y6v8g"
  APP_VERSION: ${CI_COMMIT_SHORT_SHA}
  S3_BUCKET: "siro-deployment"
  AWS_ID: ${AWS_ID}
  AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
  AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
  AWS_REGION: ap-southeast-1

image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest

build:
  stage: build
  allow_failure: false
  before_script:
    - curl -fsSL https://deb.nodesource.com/setup_18.x | bash -
    - apt-get install -y nodejs && node -v
  script: |
    echo "Start build"
    npm i && npm run build
    cp -a dist/. public/
    echo "Creating zip file"
    cd public && zip -r ${APP_NAME}.zip .
    AWS_VERSION_LABEL=${APP_NAME}-${CI_PIPELINE_ID}-${CI_COMMIT_BRANCH}-${APP_VERSION}
    S3_KEY="$AWS_VERSION_LABEL.zip"
    echo "Uploading to S3"
    aws s3 cp ${APP_NAME}.zip s3://${S3_BUCKET}/superadmin-front/${S3_KEY} --region ${AWS_REGION}
  only:
    refs:
      - dev
      - main

dev_deploy:
  stage: dev
  allow_failure: false
  needs: [build]
  script: |
    AWS_VERSION_LABEL=${APP_NAME}-${CI_PIPELINE_ID}-${CI_COMMIT_BRANCH}-${APP_VERSION}
    S3_KEY="$AWS_VERSION_LABEL.zip"
    aws amplify start-deployment \
      --app-id $APP_ID \
      --branch-name dev \
      --source-url https://${S3_BUCKET}.s3.ap-southeast-1.amazonaws.com/superadmin-front/${S3_KEY} \
      --version AWS_VERSION_LABEL
      
  only:
    refs:
      - dev

main_deploy:
  stage: prod
  allow_failure: false
  when: manual
  needs: [build]
  script: |
    AWS_VERSION_LABEL=${APP_NAME}-${CI_PIPELINE_ID}-${CI_COMMIT_BRANCH}-${APP_VERSION}
    S3_KEY="$AWS_VERSION_LABEL.zip"
    aws amplify start-deployment \
      --app-id $APP_ID \
      --branch-name main \
      --source-url https://${S3_BUCKET}.s3.ap-southeast-1.amazonaws.com/superadmin-front/${S3_KEY} \
      --version AWS_VERSION_LABEL
  only:
    refs:
      - main
