/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LoginImport } from './routes/login'
import { Route as DashboardImport } from './routes/_dashboard'
import { Route as DashboardIndexImport } from './routes/_dashboard/index'
import { Route as DashboardStoresIndexImport } from './routes/_dashboard/stores.index'
import { Route as DashboardNotificationIndexImport } from './routes/_dashboard/notification.index'
import { Route as DashboardStoresStoreidImport } from './routes/_dashboard/stores.$storeid'

// Create/Update Routes

const LoginRoute = LoginImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const DashboardRoute = DashboardImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRoute,
} as any)

const DashboardIndexRoute = DashboardIndexImport.update({
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)

const DashboardStoresIndexRoute = DashboardStoresIndexImport.update({
  path: '/stores/',
  getParentRoute: () => DashboardRoute,
} as any)

const DashboardNotificationIndexRoute = DashboardNotificationIndexImport.update(
  {
    path: '/notification/',
    getParentRoute: () => DashboardRoute,
  } as any,
)

const DashboardStoresStoreidRoute = DashboardStoresStoreidImport.update({
  path: '/stores/$storeid',
  getParentRoute: () => DashboardRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_dashboard': {
      preLoaderRoute: typeof DashboardImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/_dashboard/': {
      preLoaderRoute: typeof DashboardIndexImport
      parentRoute: typeof DashboardImport
    }
    '/_dashboard/stores/$storeid': {
      preLoaderRoute: typeof DashboardStoresStoreidImport
      parentRoute: typeof DashboardImport
    }
    '/_dashboard/notification/': {
      preLoaderRoute: typeof DashboardNotificationIndexImport
      parentRoute: typeof DashboardImport
    }
    '/_dashboard/stores/': {
      preLoaderRoute: typeof DashboardStoresIndexImport
      parentRoute: typeof DashboardImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  DashboardRoute.addChildren([
    DashboardIndexRoute,
    DashboardStoresStoreidRoute,
    DashboardNotificationIndexRoute,
    DashboardStoresIndexRoute,
  ]),
  LoginRoute,
])

/* prettier-ignore-end */
